/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicEstudarRouteImport } from './routes/api/public/estudar'
import { Route as ApiPublicAppAuthProjetoRouteImport } from './routes/api/public/app-auth.$projeto'
import { Route as ApiPublicAppPrivateProjetoColecaoRouteImport } from './routes/api/public/app-private.$projeto.$colecao'
import { Route as ApiPublicDadosProjetoColecaoRouteImport } from './routes/api/public/dados.$projeto.$colecao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEstudarRoute = ApiPublicEstudarRouteImport.update({
  id: '/api/public/estudar',
  path: '/api/public/estudar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppAuthProjetoRoute = ApiPublicAppAuthProjetoRouteImport.update({
  id: '/api/public/app-auth/$projeto',
  path: '/api/public/app-auth/$projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppPrivateProjetoColecaoRoute =
  ApiPublicAppPrivateProjetoColecaoRouteImport.update({
    id: '/api/public/app-private/$projeto/$colecao',
    path: '/api/public/app-private/$projeto/$colecao',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDadosProjetoColecaoRoute =
  ApiPublicDadosProjetoColecaoRouteImport.update({
    id: '/api/public/dados/$projeto/$colecao',
    path: '/api/public/dados/$projeto/$colecao',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/estudar': typeof ApiPublicEstudarRoute
  '/api/public/app-auth/$projeto': typeof ApiPublicAppAuthProjetoRoute
  '/api/public/app-private/$projeto/$colecao': typeof ApiPublicAppPrivateProjetoColecaoRoute
  '/api/public/dados/$projeto/$colecao': typeof ApiPublicDadosProjetoColecaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/estudar': typeof ApiPublicEstudarRoute
  '/api/public/app-auth/$projeto': typeof ApiPublicAppAuthProjetoRoute
  '/api/public/app-private/$projeto/$colecao': typeof ApiPublicAppPrivateProjetoColecaoRoute
  '/api/public/dados/$projeto/$colecao': typeof ApiPublicDadosProjetoColecaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/estudar': typeof ApiPublicEstudarRoute
  '/api/public/app-auth/$projeto': typeof ApiPublicAppAuthProjetoRoute
  '/api/public/app-private/$projeto/$colecao': typeof ApiPublicAppPrivateProjetoColecaoRoute
  '/api/public/dados/$projeto/$colecao': typeof ApiPublicDadosProjetoColecaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/estudar'
    | '/api/public/app-auth/$projeto'
    | '/api/public/app-private/$projeto/$colecao'
    | '/api/public/dados/$projeto/$colecao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/estudar'
    | '/api/public/app-auth/$projeto'
    | '/api/public/app-private/$projeto/$colecao'
    | '/api/public/dados/$projeto/$colecao'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/estudar'
    | '/api/public/app-auth/$projeto'
    | '/api/public/app-private/$projeto/$colecao'
    | '/api/public/dados/$projeto/$colecao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicEstudarRoute: typeof ApiPublicEstudarRoute
  ApiPublicAppAuthProjetoRoute: typeof ApiPublicAppAuthProjetoRoute
  ApiPublicAppPrivateProjetoColecaoRoute: typeof ApiPublicAppPrivateProjetoColecaoRoute
  ApiPublicDadosProjetoColecaoRoute: typeof ApiPublicDadosProjetoColecaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/estudar': {
      id: '/api/public/estudar'
      path: '/api/public/estudar'
      fullPath: '/api/public/estudar'
      preLoaderRoute: typeof ApiPublicEstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-auth/$projeto': {
      id: '/api/public/app-auth/$projeto'
      path: '/api/public/app-auth/$projeto'
      fullPath: '/api/public/app-auth/$projeto'
      preLoaderRoute: typeof ApiPublicAppAuthProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-private/$projeto/$colecao': {
      id: '/api/public/app-private/$projeto/$colecao'
      path: '/api/public/app-private/$projeto/$colecao'
      fullPath: '/api/public/app-private/$projeto/$colecao'
      preLoaderRoute: typeof ApiPublicAppPrivateProjetoColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dados/$projeto/$colecao': {
      id: '/api/public/dados/$projeto/$colecao'
      path: '/api/public/dados/$projeto/$colecao'
      fullPath: '/api/public/dados/$projeto/$colecao'
      preLoaderRoute: typeof ApiPublicDadosProjetoColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicEstudarRoute: ApiPublicEstudarRoute,
  ApiPublicAppAuthProjetoRoute: ApiPublicAppAuthProjetoRoute,
  ApiPublicAppPrivateProjetoColecaoRoute:
    ApiPublicAppPrivateProjetoColecaoRoute,
  ApiPublicDadosProjetoColecaoRoute: ApiPublicDadosProjetoColecaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
