// This file is automatically generated and enhanced with offline/resilient auth fallback.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { supabase as clientSupabase } from "./client";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" })
  .client(async ({ next }) => {
    let token: string | undefined;
    try {
      const { data } = await clientSupabase.auth.getSession();
      token = data?.session?.access_token;
    } catch {
      // ignore
    }

    const headers: Record<string, string> = {};

    if (token && token.split(".").length === 3) {
      headers["Authorization"] = `Bearer ${token}`;
    }

    if (typeof window !== "undefined") {
      let stableId = localStorage.getItem("faby_stable_device_id");
      if (!stableId) {
        stableId =
          typeof crypto !== "undefined" && crypto.randomUUID
            ? crypto.randomUUID()
            : "local_" + Math.random().toString(36).slice(2);
        localStorage.setItem("faby_stable_device_id", stableId);
      }
      headers["x-faby-device-id"] = stableId;

      let localSession = localStorage.getItem("faby_user_session");
      if (!localSession) {
        const novaSessao = {
          id: stableId,
          email: "usuario@fabyclaud.local",
          created_at: new Date().toISOString(),
        };
        localSession = JSON.stringify(novaSessao);
        localStorage.setItem("faby_user_session", localSession);
      }

      if (localSession) {
        try {
          const parsed = JSON.parse(localSession);
          if (parsed?.id) {
            headers["x-faby-local-user"] = parsed.id;
            if (parsed.email) headers["x-faby-local-email"] = parsed.email;
          }
        } catch {
          // ignore
        }
      }

      const localKeys = localStorage.getItem("faby_local_keys");
      if (localKeys && localKeys !== "{}") {
        headers["x-faby-local-keys"] = encodeURIComponent(localKeys);
      }
    }

    return next({ headers });
  })
  .server(async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"] || "https://placeholder-project.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env["SUPABASE_PUBLISHABLE_KEY"] || "placeholder-anon-key";

    const request = getRequest();
    const authHeader = request?.headers?.get("authorization");
    let token = "";
    if (authHeader && authHeader.startsWith("Bearer ")) {
      token = authHeader.replace("Bearer ", "").trim();
    }

    const isValidJwt = Boolean(
      token &&
        token !== "local-session-token" &&
        token.split(".").length === 3 &&
        !token.includes("local"),
    );

    const globalConfig: { fetch: typeof fetch; headers?: Record<string, string> } = {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    };
    if (isValidJwt) {
      globalConfig.headers = { Authorization: `Bearer ${token}` };
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: globalConfig,
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const localUserIdHeader = request?.headers?.get("x-faby-local-user")?.trim();
    const localEmailHeader = request?.headers?.get("x-faby-local-email")?.trim();
    const deviceIdHeader = request?.headers?.get("x-faby-device-id")?.trim();
    const localKeysHeader = request?.headers?.get("x-faby-local-keys")?.trim();

    let localKeysData: Record<string, { key?: string; api_url?: string }> = {};
    if (localKeysHeader) {
      try {
        localKeysData = JSON.parse(decodeURIComponent(localKeysHeader));
      } catch {
        // ignore
      }
    }

    let userId = localUserIdHeader || deviceIdHeader || "00000000-0000-0000-0000-000000000001";
    let claims: Record<string, any> = { email: localEmailHeader || "usuario@fabyclaud.local" };
    let isAutenticadoSupabase = false;

    if (isValidJwt) {
      try {
        const { data, error } = await supabase.auth.getUser(token);
        if (!error && data?.user?.id) {
          userId = data.user.id;
          claims = (data.user.app_metadata as Record<string, any>) ?? {};
          isAutenticadoSupabase = true;
        }
      } catch {
        // fallback to local userId
      }
    }

    return next({
      context: {
        supabase: supabase as any,
        userId,
        deviceId: deviceIdHeader || null,
        localUserId: localUserIdHeader || null,
        localKeys: localKeysData,
        claims,
        isAutenticadoSupabase,
      },
    });
  });
