// This file is automatically generated and enhanced with offline/resilient auth attachment.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;
    try {
      const { data } = await supabase.auth.getSession();
      token = data?.session?.access_token;
    } catch {
      // ignore
    }

    const headers: Record<string, string> = {};

    if (token && token.split(".").length === 3) {
      headers["Authorization"] = `Bearer ${token}`;
    } else if (typeof window !== "undefined") {
      const local = localStorage.getItem("faby_user_session");
      if (local) {
        try {
          const parsed = JSON.parse(local);
          if (parsed?.id) {
            headers["x-faby-local-user"] = parsed.id;
            if (parsed.email) headers["x-faby-local-email"] = parsed.email;
          }
        } catch {
          // ignore
        }
      }
    }

    return next({ headers });
  },
);
